### PR TITLE
Got full points for this one

### PR DESCRIPTION
**Pull request by ghost**
Used instance variables in HybridCar, other methods are possible as well.

### CODE REVIEW

**Comment by C0DECYCLE** [comment]
Hello Rosan!
I quickly jump in for @Perytron. Thank you very much for your solution! Its appreciated a lot! 🙏
@Patertuck and I found to minor things, to adjust before merging:
- As described in the readme please provide a meaningful commit messages for clearity and concistancy. (See: [Step 5](https://github.com/Perytron/UZH/blob/798d61d43e20e73e6e871a00a0d64b6a037219f0/README.md#step-5-just-send-it-commit--push))
- Your files "car.py" to "script.py" are correctly in a subfolder which is named correctly. However the test script should be one level above in the "Task 3 Car Types" folder. It should also be named "tests.py". (See: [Step 4](https://github.com/Perytron/UZH/blob/798d61d43e20e73e6e871a00a0d64b6a037219f0/README.md#step-4-do-your-magic-be-creative) & [Current folder structure](https://github.com/Perytron/UZH/issues/33#issuecomment-1331924915))

**Comment by Perytron** [comment]
You can leave the pull request (PR) open and just commit again to this particular branch after you have done the necessary changes. It is really quite simple! I would always add at least the exercise and what you have done with it into the commit message. That way, everyone knows what is going on; somthing like: "**Exercise 009 Task 3 Add Solution yuirike**"

**Review by C0DECYCLE — APPROVED** [review]
LGTM! (When squashing change the message to something compact and meaningful.)

**Comment by C0DECYCLE** [comment]
Congratulations! Your solution is now on main.

**Pull request merged**
