### PR TITLE
Info2-001-02: Add solution

### PR DESCRIPTION
**Pull request by ghost**
Verify my submission please.
Note that I also added a general case, that one allows users to play around and see how the code can also print out n x n matrices. The general case does not use Scanf but it keeps the functionality of the submission.

### CODE REVIEW

**Review by C0DECYCLE — CHANGES_REQUESTED** [review]
LGTM but please dont commit compiled sources (exe, etc.).

**Review by C0DECYCLE — APPROVED** [review]
LGTM!

**Review by dreamfarer — APPROVED** [review]
Thanks Rosan! 🔥 Just a reminder: Please use the commit & PR naming convention outlined in our [readme](https://github.com/Perytron/UZH#step-5-just-send-it-commit--push) next time.

**Comment by Patertuck** [comment]
Hey @yuirike

I looked over your code and tested it but it seems like you misinterpreted the task. Here is how you calculate the square of a matrix:
image

The task is very poorly written so no worries, I had difficulty understanding it in the beginning too. 😅 

In the future: Try to verify your solutions before submitting them. It would have been very easy to realize the code not resulting in the right solution by googling for a square matrix calculator.

We reopened your branch so you can add your new code onto the same one as before. So you can open a new pull request from there again.

Either way: Thanks already for contributing <3

**Pull request merged**
