### PR TITLE
Clean up 8.5 file structure and add 9.1 solution

### PR DESCRIPTION
**Pull request by C0DECYCLE**

### CODE REVIEW

**Comment by Perytron** [comment]
Thank you very much! Very nice approach in 9.1!🥰 Should I always merge your changes or wait until you have done every task of the week? What do you prefer?

**Comment by C0DECYCLE** [comment]
Thanks! Personally i think its cleaner all at once... but since not everyone who might need the solutions is looking at the open PRs, its better to get them out individually to the main branch as soon as possible.

**Comment by Perytron** [comment]
Gotcha! Good argument! Will do! If you want me to change it in the future just hit me up.

**Comment by C0DECYCLE** [comment]
(solutions 9.2-9.4 will most likely be ready tomorrow)

**Pull request merged**
