### PR TITLE
Added Psolution on Exercise 10 Task 1

### PR DESCRIPTION
**Pull request by paul891112**

### CODE REVIEW

**Comment by Perytron** [comment]
Ciao Paul, @paul891112 ! We are currently restructuring our repository, therefore I'll have to wait with merging it until this has been finished later today. Thanks for contributing! 💓

**Comment by paul891112** [comment]
> Ciao Paul, @paul891112 ! We are currently restructuring our repository, therefore I'll have to wait with merging it until this has been finished later today. Thanks for contributing! 💓

Hi guys, sorry to bother u and no problem, thank you for your hard work ❤️

**Comment by Patertuck** [comment]
@paul891112 if you wish to contribute to the repository with your solutions in the future we can add you as contributor. After the update this will allow you to use the new method of forking new branches instead of the whole repository, which is a lot better to keep the repository clean without duplications up and around. As @Perytron mentioned, this is something you will be able to read into on how to do in the new ReadMe or we can assist you. 😄

**Comment by C0DECYCLE** [comment]
@paul891112, thank you very much for your solution from my side! 
...When the new file structure is up, you have to do minor adjustment to your PR, but wont be a big deal. 👍

**Review by Perytron — APPROVED** [review]
Needs changes to structure, however, because main is protected, I firstly need to migrate it to another branch.

**Comment by paul891112** [comment]
@Patertuck Thx for the offer, ill take a closer look at the new ReadMe once its available. Until then, i dont wanna cause u guys more trouble, alot of what ur doing is actually beyond my knowledge 😅

@C0DECYCLE No problem, just let me now what i have to do any time. If the structure gets complicated with my push request, just ignore it and ill reupload it when u guys are done 👍 

And again, thanks yall for the hard work, ur the avengers for alot of students out there ❤️

**Comment by C0DECYCLE** [comment]
(New readme should be available on the main branch.)

**Comment by paul891112** [comment]
Yep my bad, just saw it after i commented

**Comment by C0DECYCLE** [comment]
@paul891112 Tipp/friendly appeal to please write commit and other git messages in the english form of present. (e.g. Add instead of Added) This might be counter intuitive but is a wide spread standard through out the industry. If requested i can explain the reasoning behind it. Thank you very much! (It will soon be added to the readme.)

**Comment by paul891112** [comment]
> 

Thanks for the tipp, ill stick to that convention.

**Pull request merged**
