### PR TITLE
Add Patertuck Solution 10.1

### PR DESCRIPTION
**Pull request by Patertuck**

### CODE REVIEW

**Comment by Perytron** [comment]
I'll merge it as soon as @C0DECYCLE has committed the restructuring of the exercises. 🙏🏽

**Comment by Perytron** [comment]
Very nice! 🔥 Thanks for the tests!

**Comment by Perytron** [comment]
Nothing serious just a heads up; next time, you could add me as **Reviewer**, yourself as **Assignees** and lable it with **solution** directly. 😁

**Comment by Patertuck** [comment]
> Nothing serious just a heads up; next time, you could add me as **Reviewer**, yourself as **Assignees** and lable it with **solution** directly. 😁

Oh yes, thanks. I will do that in the future.

**Review by Perytron — APPROVED** [review]
I've changed the folder structure to meet our newly defined standard.

**Pull request merged**
