### PR TITLE
Add 11.2 solution with types

### PR DESCRIPTION
**Pull request by C0DECYCLE**

### CODE REVIEW

**Review by Patertuck — APPROVED** [review]
LGTM!

**Comment by Patertuck** [comment]
> Thanks for reviewing!

For this its better to just merge commit, right? Only squash and commit for PR that have many commits that can be summarized in one commit.

**Comment by C0DECYCLE** [comment]
yes exactly

**Comment by Perytron** [comment]
> > Thanks for reviewing!
> 
> For this its better to just merge commit, right? Only squash and commit for PR that have many commits that can be summarized in one commit.

It does not make any difference, does it? I always use the squash thingy, even if it's just one commit. Then I don't have to think ... 🤣

**Pull request merged**
