### PR TITLE
9.2 - 9.3 solutions with types

### PR DESCRIPTION
**Pull request by C0DECYCLE**

### CODE REVIEW

**Comment by C0DECYCLE** [comment]
All (9.1 - 9,4) full point solutions are now up

**Comment by Perytron** [comment]
Wow! So cool! Thank you so much!

**Comment by Perytron** [comment]
Hey Noah (I hope this is the right name, I've found it on your website 😆), 
I just wanted to let you know that your code is ungodly beautiful and elegant. 😍 The explicit typing is just awe, I need to learn that too, how awesome! 
Thanks for your valuable contributions, it shows us others what we really should aim for, haha!

**Comment by C0DECYCLE** [comment]
Hello Gianluca
Yes Noah is right :)
Im quite flattered i have to say, you absolutely made my day😊 Thank you very much!

Yes indeed typing is a hugely valuable tool, when code gets more complex. Although in standard python these types are just hints and are not actually enforced in runtime. Nonetheless they assist you while coding and most IDEs help you prevent TypeErrors etc. 

I originally got into coding about 8 years ago but i only started to use static typed languages or types generally in the last 3 years since i got more professional about it. Before i didn’t like types at all and avoided them but since i recognized there potential i want to do everything with types 🤓.
-> Recommend it, 10/10

Im very happy i learned about this repo. I think its a great idea/project and i love to contribute/share my solutions. :)

PS: Don’t hesitate to hit me up, if there’s any question i could help with!

**Comment by Perytron** [comment]
Hey Noah! 
It is so nice to get to know you 😄. You are in assessment too, right? So we have Mikroökonomik, BWL and so on together?

I think JavaScript is the language I have spent the most time in, and, I don't think I need to elaborate more on this regarding typing... 😆 I've tried TypeScript once, but would need to look into it more. Actually, C++ was my first language. I've programmed a scale plane autopilot with it on the Arduino for my Matura papers. However, I've never properly learned to program until now. It is so funny looking back at all the filthy solutions I've implemented. And even now when I have a look at your solutions I have the feeling I am still at square one, haha! So great! 😍 

I am very happy that this repo is regarded as the main source of solution in this year's course. I mean, every Monday at least 80 people visit the repo, according to the statistics. My goal is that we can use it further along the bachelor course. We'll see how that goes! Thank you so much for contributing and giving advice, it is soooo appreciated. 

Thank you so much! I've spent way too long on this. But the main thing is that I've learned new things :)

**Comment by C0DECYCLE** [comment]
The pleasure is all mine! Yes, that’s right im in assessment as well. (major softwaresystems)

Javascript/Typescript is actually my favourite language which I used the longest! Saw your Babylon project, very nice! I’m big fan of Babylon. Also very cool Matura paper, congratulations on that project.
I myself am very very far from absolution. I think that’s the beauty of IT/Software, there’s infinite learning potential and always new exciting stuff around every corner.

Very cool/interesting statistic. I would love to further contribute/help out in future! Thank you for the lovely messages!

**Pull request merged**
