### PR TITLE
Add Paul891112 Solution 11.1, 11.2, 11.3, 11.4 

### PR DESCRIPTION
**Pull request by paul891112**

### CODE REVIEW

**Comment by paul891112** [comment]
I forgot to commit the changes before pushing hahaha f*** me, please ignore this PR

**Comment by C0DECYCLE** [comment]
👍 and i noticed other commits there?

**Comment by paul891112** [comment]
@Perytron Thats what im trying to do, but now im stuck. So I renamed all my directories locally. When im on windows command line, i can see the folder names are "Paul891112 Solution". Then i called up git add, commit, push. However, on github its still "paul891112 Solution". I repeated this 3 times, restarted command line, delete and create new branch on github,... Ill need some fresh air then ill try again 😅 

@C0DECYCLE Yea i find them annoying, i have two local branches, one main with paul... and another one called "011-10203-paul891112-solution" with Paul... No matter which local branch i push to remote branch, the remote branch stays paul..., im getting more and more depressed 💀

**Comment by paul891112** [comment]
Nope. -f is not working, ill try again tomorrow

**Pull request closed without merging**
