### PR TITLE
E11 T1234 Paul891112 Solution

### PR DESCRIPTION
**Pull request by paul891112**
Add solution to Tasks 1,2,3,4 in Exercise 11, remember to add public. to import statements and change file path back to requirement of Access before submitting

### CODE REVIEW

**Comment by C0DECYCLE** [comment]
Thanks a lot for the solutions! gonna review it in a sec.

**Comment by C0DECYCLE** [comment]
One thing... we need to discuss a procedure for multiple solutions at once... i almost fell off my chair after seeing your branch name😅

**Comment by paul891112** [comment]
Hahaha surprise! But is this a big issue? Im used to finish all tasks and upload it all together. How about we change the branch naming convention to something like E011-T1T2T3-USERNAME-DESCRIPTION? I could also reupload task by task and continue so from now on.

**Comment by C0DECYCLE** [comment]
for this branch its ok like this, but i'll open a issue where we can discuss branch conventions in this matter.

**Review by C0DECYCLE — COMMENTED** [review]
Please change your p in paul... Solution to uppercase, to match naming conventions.

**Comment by paul891112** [comment]
> Please change your p in paul... Solution to uppercase, to match naming conventions.

Did i understand you correctly this way?

**Comment by C0DECYCLE** [comment]
> > Please change your p in paul... Solution to uppercase, to match naming conventions.
> 
> Did i understand you correctly this way?

no sorry i meant the directory name

**Comment by paul891112** [comment]
Got it, anyways ill reupload everything in the correct format after the branch naming convention issue is solved. Lets consider this pull request as closed

**Comment by C0DECYCLE** [comment]
i apologise for the chaos 🙏

**Comment by C0DECYCLE** [comment]
Thank you @Perytron for the clarification! 
Of course also a big big thank you for your contribution! ❤️ Sorry for being too harsch.

**Comment by paul891112** [comment]
Hey guys, no worries were good, not upset or anything 🤣 sorry if i sent the wrong message, my texts are quite straight forward cuz i want to be efficient when communicating, that turns out to be rude or have a passive aggressive tone 😅 i also appreciate it when u guys let me know i did something wrong, just wanted to make sure i understand the correct way first and then execute

@Perytron Got it, ill start a new pull request in a while with the correct naming convention this time

Love u guys hahaha thx for being patient and thoughtful

**Pull request closed without merging**
